name: remain
publish_to: 'none' 
version: 3.0.12+1

environment:
  sdk: '>=3.6.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter

  ###CORE PACKAGES##################
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.0
  hooks_riverpod: ^2.4.5
  flutter_hooks: ^0.21.2
  shared_preferences: ^2.2.2
  built_collection: ^5.1.1
  easy_date_timeline: ^2.0.4
  freezed_annotation: ^2.4.1
  auto_route: ^7.3.2
  stack_trace: ^1.11.0
  logger: ^2.0.2+1
  fluttertoast: ^8.2.2
  json_annotation: ^4.8.1
  timezone: ^0.10.0
  intl: ^0.20.2
  provider: ^6.1.1
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  http: ^1.2.1
  readmore: ^3.0.0
  table_calendar: ^3.1.2
  webview_flutter_wkwebview: ^3.22.0

  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_adaptive_scaffold: ^0.3.3+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^12.0.0+1
  flutter_downloader: ^1.11.7
  sn_progress_dialog: ^1.1.4
  rxdart: ^0.28.0
  flutter_html: ^3.0.0-beta.2
  drop_down_list: ^2.0.0
  rotated_corner_decoration: ^2.1.0+1
  lottie: ^3.1.0

  tabby_flutter_inapp_sdk: ^1.5.0
  motion_tab_bar: ^2.0.4
  convex_bottom_bar: ^3.2.0
  restart_app: ^1.3.2
  share_plus: ^11.0.0

  
  
 


  ###RESPONSIVE#####################
  responsive_builder: ^0.7.0
  get_it: ^8.0.2


  ###UI ENHANCEMENT#####################
  showcaseview: ^4.0.1
  skeletonizer: ^2.0.1
  badges: ^3.1.2
  pinput: ^5.0.0
  #flutter_credit_card: ^4.0.1
  flutter_blurhash: ^0.9.1
  # intl_phone_number_input:
  #   git:
  #     url: https://github.com/Shahidbangash/intl_phone_number_input.git
  #     ref: develop 
 # intl_phone_number_input: ^0.7.3+1
  flutter_side_menu: ^0.5.41
  #country_code_picker: ^3.0.0
  multi_select_flutter: ^4.1.3
  pin_code_fields: ^8.0.1


############HELPERS #################################
  file_picker: ^10.2.0
  url_launcher: ^6.2.2
  faker: ^2.1.0
  crypto: ^3.0.3
  uuid: ^4.1.0
  json_path: ^0.7.0
  package_info_plus: ^8.1.1
  geolocator: ^14.0.1
  path_provider: ^2.1.1
  url_strategy: ^0.3.0
  modal_bottom_sheet: ^3.0.0
  persistent_bottom_nav_bar: ^6.2.1
  floating_bottom_bar: ^0.0.2
  flutter_launcher_icons: ^0.14.1
  credit_card_validator: ^2.1.0
  credit_card_type_detector: ^3.0.0
  month_year_picker: ^0.5.0+1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  auto_size_text: ^3.0.0
  #extended_phone_number_input: ^1.0.2
  intl_phone_number_input: ^0.7.4
  awesome_dialog: ^3.2.0
  syncfusion_flutter_pdfviewer: ^29.2.10
  flutter_pdfview: ^1.3.2
  material_design_icons_flutter: ^7.0.7296
  image_picker: ^1.1.2
  moyasar: ^2.0.7
  pay: ^3.2.1
  intl_utils: ^2.8.7
  webview_flutter: ^4.10.0
  google_maps_flutter: ^2.12.1
  syncfusion_flutter_charts: ^29.2.11
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^7.3.2
  custom_lint: ^0.7.0 # other lints depend on this
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  random_string: ^2.3.1
  build_runner: ^2.1.10
  freezed: ^2.4.5
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.8
  hive_generator: ^2.0.1
  change_app_package_name: ^1.1.0
  analyzer: ^6.7.0

flutter:
  generate: true
  uses-material-design: true
 
  assets:
    - assets/images/
    - assets/svg/
    - assets/svg/icons/
    - assets/svg/vectors/
    - assets/lottie/

  fonts:
    - family: englishFont
      fonts:
        - asset: assets/fonts/english-font.ttf
          weight: 400

    - family: arabicFont
      fonts:
        - asset: assets/fonts/arabic-font.OTF
          weight: 600

    
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/remain_logo.png"
  web:
    generate: true
  

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n/arb
  output_dir: lib/l10n/generated